# 多数据源配置
spring:
  main:
    allow-bean-definition-overriding: true
  primary:
    datasource:
      jdbc-url: jdbc:mysql://rm-uf6h9e68kb6607379ho.mysql.rds.aliyuncs.com:3306/quzhuanxiang?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
      username: starbaba
      password: '!Q2w#E4r%t'
      #driver-class-name: com.mysql.jdbc.Driver

#secondary
  secondary:
    datasource:
      jdbc-url: jdbc:mysql://rm-uf6h9e68kb6607379ho.mysql.rds.aliyuncs.com:3306/activity?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
      username: starbaba
      password: '!Q2w#E4r%t'
      #driver-class-name: com.mysql.jdbc.Driver

#tertiary
  tertiary:
    datasource:
      jdbc-url: jdbc:mysql://rm-uf6h9e68kb6607379ho.mysql.rds.aliyuncs.com:3306/quzhuanxiang_account?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
      username: starbaba
      password: '!Q2w#E4r%t'
      #driver-class-name: com.mysql.jdbc.Driver

# jpa 配置
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  generate-ddl: false
  thymeleaf:
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:templates/,classpath:static/

# rabbitmq 配置信息
  #rabbitmq:
    #host: localhost
    #port: 5672
    #username: guest
    #password: guest

    #整合rabbitmq消费者
    #listener:
      #concurrency: 5
      #max-concurrency: 10
      #签收模式
      #acknowledge-mode: manual
      #限流 - 每次只消费一条
      #prefetch: 1

#redis配置
  redis:
    host: 139.196.82.192
    password: vipgiftQuzhuanxiang
    database: 0
    port: 6379
    timeout: 3S

# 端口配置,  默认8080
server:
  port: 8080
